### ISSUE TITLE
Unknown Battery Meter State from XML

### ISSUE THREAD

**Issue by sami-eljabali** [eo/battery-meter-view#1]
Hello EO,

Thanks for the project, it looks great! 😃 

I was wondering if there's a way to set the battery mode to `unknown` from the XML? If not, I would suggest it be done by having an attribute along the lines of:

```xml
app:batteryMeterState="{unknown, charging, regular, critical}"
```

Thanks!

**Comment by eo** [comment]
Hi @seljabali,

If you do not provide `batteryMeterChargeLevel` and `batteryMeterIsCharging` attributes in your XML, battery state should be unknown. Let me know if that works?

Thanks

**Comment by sami-eljabali** [comment]
Will do for now! Thanks EO.
